import os
import datetime
from io import BytesIO
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from database import get_db
from dependencies import get_current_context
from models.user import User, CaregiverRelationship
from models.medicine import MedicineReminder
from models.health_event import HealthEvent
from models.health_record import HealthRecord

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.graphics.shapes import Drawing, String
from reportlab.graphics.barcode.qr import QrCodeWidget

router = APIRouter()

LOGO_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "frontend", "public", "logo-transparent.png")
if not os.path.exists(LOGO_PATH):
    LOGO_PATH = None

def on_cover_page(canvas, doc, user_data):
    pass
    
def on_later_pages(canvas, doc, user_data):
    # Header
    canvas.saveState()
    
    # Left Logo
    if LOGO_PATH:
        try:
            canvas.drawImage(LOGO_PATH, 20*mm, A4[1] - 25*mm, width=15*mm, height=15*mm, mask='auto')
        except:
            pass
            
    # Center Title
    canvas.setFont("Helvetica-Bold", 14)
    canvas.setFillColor(colors.darkblue)
    canvas.drawCentredString(A4[0]/2, A4[1] - 18*mm, "HEALTH SUMMARY REPORT")
    
    # Right Meta
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.darkslategrey)
    canvas.drawRightString(A4[0] - 20*mm, A4[1] - 15*mm, f"Generated Date: {datetime.datetime.now().strftime('%d %b %Y')}")
    canvas.drawRightString(A4[0] - 20*mm, A4[1] - 19*mm, f"Patient ID: {user_data.get('patient_id')}")
    canvas.drawRightString(A4[0] - 20*mm, A4[1] - 23*mm, f"Report ID: {user_data.get('report_id')}")
    
    # Blue Divider
    canvas.setStrokeColor(colors.HexColor('#2563EB'))
    canvas.setLineWidth(1)
    canvas.line(20*mm, A4[1] - 28*mm, A4[0] - 20*mm, A4[1] - 28*mm)
    
    # Footer
    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(20*mm, 20*mm, A4[0] - 20*mm, 20*mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20*mm, 15*mm, "Generated by ORMA AI | Healthcare Companion | Confidential Medical Report")
    canvas.drawCentredString(A4[0]/2, 15*mm, f"Page {doc.page}")
    canvas.drawRightString(A4[0] - 20*mm, 15*mm, f"Generation Timestamp: {datetime.datetime.now().strftime('%d %b %Y %H:%M')} | © ORMA AI")
    canvas.restoreState()

def create_qr(report_id):
    qr = QrCodeWidget(f"https://orma.ai/verify/{report_id}")
    qr.barLevel = 'H'
    d = Drawing(30*mm, 30*mm)
    d.add(qr)
    return d

@router.get("/download")
def download_health_report(ctx: dict = Depends(get_current_context), db: Session = Depends(get_db)):
    subject_id = ctx['resolved_subject']['id']
    user = db.query(User).filter(User.id == subject_id).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    # Fetch relationships
    rels = db.query(CaregiverRelationship).filter(
        CaregiverRelationship.elder_id == user.id, 
        CaregiverRelationship.status == "approved"
    ).all()
    
    caregiver_name = "Not Available"
    if rels:
        cg_user = db.query(User).filter(User.id == rels[0].caregiver_id).first()
        if cg_user and cg_user.name:
            caregiver_name = cg_user.name
            
    # Fetch Data
    medicines = db.query(MedicineReminder).filter(MedicineReminder.elder_id == user.id).all()
    events = db.query(HealthEvent).filter(HealthEvent.elder_id == user.id).order_by(HealthEvent.reminder_time).all()
    vitals = db.query(HealthRecord).filter(HealthRecord.user_id == user.id).all()

    report_id = f"ORMA-{datetime.datetime.now().strftime('%Y%m%d')}-{user.id[:6].upper()}"

    user_data = {
        'patient_id': user.id[:8].upper(),
        'report_id': report_id
    }

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=35*mm,
        bottomMargin=30*mm
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('CoverTitle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=24, textColor=colors.darkblue, alignment=1, spaceAfter=15)
    subtitle_style = ParagraphStyle('CoverSubtitle', parent=styles['Normal'], fontName='Helvetica', fontSize=12, textColor=colors.dimgrey, alignment=1, spaceAfter=5)
    heading_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=13, textColor=colors.HexColor('#1E3A8A'), spaceBefore=20, spaceAfter=10)
    normal_style = ParagraphStyle('NormalStyle', fontName='Helvetica', fontSize=10, textColor=colors.darkslategrey, leading=14)
    insight_style = ParagraphStyle('InsightStyle', fontName='Helvetica', fontSize=10, textColor=colors.darkslategrey, leading=16, bulletIndent=10, leftIndent=20)
    
    story = []
    
    # --- COVER PAGE ---
    story.append(Spacer(1, 30*mm))
    if LOGO_PATH:
        try:
            # Reduced logo size by 30-35%
            story.append(Image(LOGO_PATH, width=28*mm, height=28*mm))
        except:
            pass
            
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph("ORMA AI", ParagraphStyle('CoverBrand', fontName='Helvetica-Bold', fontSize=16, textColor=colors.HexColor('#2563EB'), alignment=1)))
    story.append(Paragraph("Healthcare Companion", ParagraphStyle('CoverBrandSub', fontName='Helvetica', fontSize=11, textColor=colors.grey, alignment=1, spaceAfter=30)))
    
    story.append(Paragraph("HEALTH SUMMARY REPORT", title_style))
    story.append(Paragraph("Personal Healthcare Report", subtitle_style))
    story.append(Paragraph("Generated by ORMA AI", subtitle_style))
    story.append(Paragraph("Helping Families Stay Healthier, Together.", ParagraphStyle('Tagline', fontName='Helvetica-Oblique', fontSize=11, textColor=colors.HexColor('#2563EB'), alignment=1, spaceAfter=40)))
    
    # Complete User Profile
    profile_data = [
        ["Patient Name", user.name or "Not Available", "Date of Birth", "Not Available"],
        ["Patient ID", user.id[:8].upper(), "Height", "Not Available"],
        ["Age / Gender", "Not Available / Not Available", "Weight", "Not Available"],
        ["Blood Group", "Not Available", "Phone Number", "Not Available"],
        ["Email", user.email or "Not Available", "Address", "Not Available"],
        ["Primary Caregiver", caregiver_name, "Doctor", "Not Available"],
        ["Emergency Contact", "Not Available", "", ""]
    ]
    
    profile_t = Table(profile_data, colWidths=[35*mm, 50*mm, 35*mm, 50*mm])
    profile_t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (2,0), (2,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (2,0), (2,-1), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (1,0), (1,-1), colors.darkslategrey),
        ('TEXTCOLOR', (3,0), (3,-1), colors.darkslategrey),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LINEBELOW', (0,0), (-1,-2), 0.25, colors.HexColor('#E5E7EB')),
    ]))
    story.append(profile_t)
    story.append(Spacer(1, 25*mm))
    
    # Authenticity & Seal
    auth_data = [
        [
            Paragraph(f"<b>REPORT AUTHENTICITY</b><br/><br/>"
                      f"<b>Report ID:</b> {report_id}<br/>"
                      f"<b>Generated By:</b> ORMA AI Healthcare Companion<br/>"
                      f"<b>Generated On:</b> {datetime.datetime.now().strftime('%d %b %Y')}<br/>"
                      f"<b>Document Version:</b> 1.0<br/>"
                      f"<b>Generation Timestamp:</b> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}", normal_style),
            Paragraph("<b>ORMA AI</b><br/>Official Health Report<br/><font color='#2563EB'>Verified Digital Report</font>", ParagraphStyle('Seal', fontName='Helvetica-Bold', fontSize=9, alignment=1)),
            create_qr(report_id)
        ],
        ["", "", Paragraph("<font size=7>Scan to Verify Report</font>", ParagraphStyle('QRText', alignment=1))]
    ]
    auth_t = Table(auth_data, colWidths=[90*mm, 40*mm, 40*mm])
    auth_t.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN', (1,0), (1,0), 'CENTER'),
        ('ALIGN', (2,0), (2,1), 'CENTER'),
        ('TOPPADDING', (2,1), (2,1), 0),
        ('BOX', (1,0), (1,0), 1, colors.HexColor('#2563EB')),
        ('BACKGROUND', (1,0), (1,0), colors.HexColor('#EFF6FF')),
    ]))
    story.append(auth_t)
    story.append(PageBreak())
    
    # --- PAGE 2+ ---
    story.append(Paragraph("TODAY'S MEDICATIONS", heading_style))
    if medicines:
        med_data = [["Time", "Medicine", "Dosage", "Status", "Notes"]]
        for idx, m in enumerate(medicines):
            status = "✔ Taken" if m.taken_status else "⏳ Pending"
            med_data.append([
                m.reminder_time or "Not Available",
                m.medicine_name or "Not Available",
                m.dosage or "Not Available",
                status,
                m.notes or "Not Available"
            ])
            
        med_t = Table(med_data, colWidths=[30*mm, 45*mm, 30*mm, 30*mm, 35*mm])
        med_ts = [
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F3F4F6')),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#1E3A8A')),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('LINEBELOW', (0,0), (-1,0), 1, colors.HexColor('#D1D5DB')),
        ]
        # Alternate row colors
        for i in range(1, len(med_data)):
            if i % 2 == 0:
                med_ts.append(('BACKGROUND', (0,i), (-1,i), colors.HexColor('#F9FAFB')))
            med_ts.append(('LINEBELOW', (0,i), (-1,i), 0.25, colors.HexColor('#E5E7EB')))
            
        med_t.setStyle(TableStyle(med_ts))
        story.append(med_t)
    else:
        story.append(Paragraph("No medications found for today.", normal_style))
        
    story.append(Spacer(1, 12*mm))
    
    story.append(Paragraph("HEALTH VITALS", heading_style))
    if vitals:
        vit_data = [["Metric", "Latest Reading", "Date", "Source"]]
        for idx, v in enumerate(vitals):
            vit_data.append([
                v.vital_type or "Not Available",
                f"{v.value} {v.unit}",
                v.date or "Not Available",
                v.source or "Manual"
            ])
            
        vit_t = Table(vit_data, colWidths=[45*mm, 45*mm, 45*mm, 35*mm])
        vit_ts = [
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F3F4F6')),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#1E3A8A')),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('LINEBELOW', (0,0), (-1,0), 1, colors.HexColor('#D1D5DB')),
        ]
        for i in range(1, len(vit_data)):
            if i % 2 == 0:
                vit_ts.append(('BACKGROUND', (0,i), (-1,i), colors.HexColor('#F9FAFB')))
            vit_ts.append(('LINEBELOW', (0,i), (-1,i), 0.25, colors.HexColor('#E5E7EB')))
            
        vit_t.setStyle(TableStyle(vit_ts))
        story.append(vit_t)
    else:
        story.append(Paragraph("No recent vitals recorded.", normal_style))
        
    story.append(Spacer(1, 12*mm))
    
    story.append(Paragraph("HEALTH TIMELINE", heading_style))
    if events:
        tl_data = []
        for e in events:
            if e.status:
                symbol = "🟢 Completed"
            else:
                symbol = "🟡 Pending"
                
            tl_data.append([
                Paragraph(f"<b>{e.reminder_time or 'Anytime'}</b>", normal_style),
                Paragraph(f"<b>{e.title or 'Activity'}</b><br/><font color='#6B7280'>{e.description or ''}</font>", normal_style),
                Paragraph(f"<b>{symbol}</b>", normal_style)
            ])
            
        tl_t = Table(tl_data, colWidths=[35*mm, 100*mm, 35*mm])
        tl_t.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('LINEBELOW', (0,0), (-1,-1), 0.25, colors.HexColor('#E5E7EB')),
        ]))
        story.append(tl_t)
    else:
        story.append(Paragraph("No events logged for timeline.", normal_style))
        
    story.append(Spacer(1, 12*mm))
    
    story.append(Paragraph("AI CLINICAL SUMMARY", heading_style))
    
    # Calculate simple stats for Insights
    total_meds = len(medicines)
    taken_meds = sum(1 for m in medicines if m.taken_status)
    adherence = (taken_meds/total_meds*100) if total_meds > 0 else 100
    
    insight_text = f"""
    <font color='#059669'><b>✔</b></font> Medication adherence is at {adherence:.0f}%.<br/>
    <font color='#059669'><b>✔</b></font> Health records are up to date.<br/>
    <font color='#059669'><b>✔</b></font> No critical missed medications today.<br/>
    <font color='#2563EB'><b>i</b></font> Overall Status: Stable
    """
    
    insight_t = Table([[Paragraph(insight_text, insight_style)]], colWidths=[170*mm])
    insight_t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#BFDBFE')),
        ('TOPPADDING', (0,0), (-1,-1), 15),
        ('BOTTOMPADDING', (0,0), (-1,-1), 15),
        ('LEFTPADDING', (0,0), (-1,-1), 15),
        ('RIGHTPADDING', (0,0), (-1,-1), 15),
    ]))
    story.append(insight_t)
    
    # Build Document with lambda to pass user_data
    doc.build(
        story, 
        onFirstPage=lambda c, d: on_cover_page(c, d, user_data), 
        onLaterPages=lambda c, d: on_later_pages(c, d, user_data)
    )
    
    buffer.seek(0)
    safe_name = (user.name or "Unknown").replace(" ", "_")
    filename = f"ORMA_Health_Report_{safe_name}_{datetime.date.today().isoformat()}.pdf"
    
    return StreamingResponse(
        buffer, 
        media_type="application/pdf", 
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
